name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.0
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build  # outputs to ./dist

      - name: Add .nojekyll (and CNAME if using custom domain)
        run: |
          touch dist/.nojekyll
          echo 'bl4ck4t.com' > dist/CNAME

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          cname: bl4ck4t.com
